# Copyright 2022 Canonical Ltd.
# SPDX-License-Identifier: Apache-2.0
options:
  container:
    type: string
    description: The name of the Azure Storage Container
  storage-account:
    type: string
    description: The name of the Azure storage account
  secret-key:
    type: secret
    description: The secret key to connect to Azure Storage account
  path:
    type: string
    description: The path inside the bucket/container to store objects.
    default: ''
  connection-protocol:
    type: string  
    description: The storage protocol to use when connecting to Azure storage
    default: 'abfss'